version: '3'

networks:
    inception:
        name: inception
        driver: bridge

services:
    wordpress:
        build: ./requirements/wordpress/
        image: wordpress:inception
        container_name: wordpress
        env_file: .env
        restart: always
        networks:
            - inception
    nginx:
        build: ./requirements/nginx/
        image: nginx:inception
        container_name: nginx
        env_file: .env
        extra_hosts: 
            - ${LOGIN}.42.fr:127.0.0.1
        depends_on:
            - wordpress
        ports:
            - 443:443
            #- 80:80
        restart: always
        networks:
            - inception