version: '3'

networks:
    inception:
        name: inception
        driver: bridge

services:
    mariadb:
        image: mariadb:inception
        env_file: .env
        volumes:
            - db:/var/lib/mysql
        restart: always
        build: ./requirements/mariadb/
        networks:
            - inception
        container_name: mariadb
        user: root
    wordpress:
        build: ./requirements/wordpress/
        image: wordpress:inception
        container_name: wordpress
        depends_on:
            - mariadb
        env_file: .env
        volumes:
            - wp:/var/www/html
        restart: always
        networks:
            - inception
        user: root
    nginx:
        image: nginx:inception
        build: ./requirements/nginx/
        container_name: nginx
        env_file: .env
        volumes:
            - wp:/var/www/html
        depends_on:
            - wordpress
        ports:
            - "443:443"
        restart: always
        networks:
            - inception
        user: root


volumes:
    wp:
        driver: local
        name: wordpress
        driver_opts:
            type: none
            o: bind
            device: /home/pmarash/data/wp
    db:
        driver: local
        name: mariadb
        driver_opts:
            type: none
            o: bind
            device: /home/pmarash/data/db