version: '3'

networks:
    inception:
        name: inception
        driver: bridge

services:
    nginx:
        build: ./requirements/nginx/
        #    context: ./requirements/nginx/
        #    dockerfile: Dockerfile
   #args:
   # ALPINE_VERSION: ${ALPINE_VERSION}
   # NGINX_VERSION: ${NGINX_VERSION}
        image: nginx:inception
        container_name: nginx
        ports:
            - 443:443
            #- 80:80
        restart: always
        networks:
            - inception